### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [5]:
vector = np.random.rand(10)
matrix = np.array([[11,14,17],[20,23,26],[29,32,35]])

print(f"Вектор {vector.shape}:", vector)
print(f"Матриця {matrix.shape}:", matrix)

Вектор (10,): [0.08831901 0.57727614 0.38915893 0.71911365 0.74698593 0.90822826
 0.35925827 0.64701167 0.19599963 0.8555658 ]
Матриця (3, 3): [[11 14 17]
 [20 23 26]
 [29 32 35]]



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [10]:
vec_add10 = (10 + vector).round(2)
vec_add10_mult = 2 * vec_add10
vec_sq = vector**2

print("До вектора додали 10 та округлили до 2 знаків після коми:", vec_add10)
print("Попередній вектор домножили на 2:", vec_add10_mult)
print("Вектор, який містить квадрат кожного елемента початкового вектора:", vec_sq)

До вектора додали 10 та округлили до 2 знаків після коми: [10.09 10.58 10.39 10.72 10.75 10.91 10.36 10.65 10.2  10.86]
Попередній вектор домножили на 2: [20.18 21.16 20.78 21.44 21.5  21.82 20.72 21.3  20.4  21.72]
Вектор, який містить квадрат кожного елемента початкового вектора: [0.00780025 0.33324774 0.15144467 0.51712444 0.55798798 0.82487858
 0.1290665  0.4186241  0.03841586 0.73199284]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [11]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [27]:
result_matrix = np.dot(B, A)

print(f"Помножені матриці {A.shape} та {B.shape} з результатом 2x2 (result_matrix):\n", result_matrix)
print(f"Помножена матриця {result_matrix.shape} на вектор {C.shape}:\n", np.dot(result_matrix, C))
print(f"Помножена матриця {result_matrix.shape} на матрицю {D.shape}:\n", np.dot(result_matrix, D))

Помножені матриці (3, 2) та (2, 3) з результатом 2x2 (result_matrix):
 [[0.7281 0.5202]
 [0.2034 0.2846]]
Помножена матриця (2, 2) на вектор (2, 1):
 [[0.5202]
 [0.2846]]
Помножена матриця (2, 2) на матрицю (2, 2):
 [[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [33]:
print("Транспонована матриця result_matrix:\n", result_matrix.T)
print("Транспонований вектор vector:\n", vector.T)
print("Чи є зміна між vector та транспонованим vector?", not np.array_equal(vector.T, vector))

column_vector = np.expand_dims(vector, axis=1)

print("Застосовано numpy.expand_dims до vector з аргументом axis=1:\n", column_vector)
print("Чи є зміна між vector та транспонованим vector?", not np.array_equal(column_vector, vector))
#тепер це вектор у вигляді стовпця, або матриця розмірністю (10,1)

column_vector_t = column_vector.T
print(f"Транспонований вектор розміром {column_vector_t.shape}:\n", column_vector_t)
#тобто тепер ми отримали вектор у вигляді рядка, як на початку, але з розмірністю не (10,), а (1,10)

Транспонована матриця result_matrix:
 [[0.7281 0.2034]
 [0.5202 0.2846]]
Транспонований вектор vector:
 [0.08831901 0.57727614 0.38915893 0.71911365 0.74698593 0.90822826
 0.35925827 0.64701167 0.19599963 0.8555658 ]
Чи є зміна між vector та транспонованим vector? False
Застосовано numpy.expand_dims до vector з аргументом axis=1:
 [[0.08831901]
 [0.57727614]
 [0.38915893]
 [0.71911365]
 [0.74698593]
 [0.90822826]
 [0.35925827]
 [0.64701167]
 [0.19599963]
 [0.8555658 ]]
Чи є зміна між vector та транспонованим vector? True
Транспонований вектор розміром (1, 10):
 [[0.08831901 0.57727614 0.38915893 0.71911365 0.74698593 0.90822826
  0.35925827 0.64701167 0.19599963 0.8555658 ]]
